# Generated by Django 4.2.4 on 2023-08-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code_if_redirected', models.PositiveIntegerField(default=0)),
                ('http_status', models.PositiveIntegerField(default=0)),
                ('https_status', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
