# Generated by Django 4.2.4 on 2023-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_alter_domainanalysis_https_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainanalysis',
            name='http_status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='domainanalysis',
            name='https_status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
