# Generated by Django 4.2.4 on 2023-08-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_alter_domainanalysis_http_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainanalysis',
            name='http_status',
        ),
        migrations.RemoveField(
            model_name='domainanalysis',
            name='https_status',
        ),
    ]
