# Generated by Django 4.2.4 on 2023-08-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_remove_domainanalysis_http_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainanalysis',
            old_name='status_code_if_redirected',
            new_name='http_status',
        ),
        migrations.AddField(
            model_name='domainanalysis',
            name='https_status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
