# Generated by Django 4.2.4 on 2023-08-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_rename_status_code_if_redirected_domainanalysis_http_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
