# Generated by Django 4.2.4 on 2023-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_delete_domain_alter_domainanalysis_public_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainanalysis',
            name='public_ip',
            field=models.CharField(max_length=15),
        ),
    ]
