# Generated by Django 4.2.4 on 2023-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_alter_domainanalysis_public_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainanalysis',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='domainanalysis',
            name='status_code_if_redirected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
