# Generated by Django 4.2.4 on 2023-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_remove_domainanalysis_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainanalysis',
            name='redirect_status_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
