# Generated by Django 4.2.4 on 2023-10-04 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0011_domainanalysis_redirect_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainanalysis',
            name='redirect_status_code',
        ),
        migrations.RemoveField(
            model_name='domainanalysis',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='domainanalysis',
            name='status_code_if_redirected',
        ),
        migrations.AddField(
            model_name='domainanalysis',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='domainanalysis',
            name='http_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainanalysis',
            name='https_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
